const listaPeliculas = [
  "Batman",
  "Better Call Saul",
  "Hellraiser",
  "Inception",
  "The Matrix",
  "Interstellar",
  "Gladiator",
  "Titanic",
  "Avatar",
  "Dark",
  "The Godfather",
  "Pulp Fiction",
  "Fight Club",
  "Bleach",
  "The Dark Knight",
  "Forrest Gump",
  "Joker",
  "Chernobyl",
  "Whiplash",
  "Dragon Ball Z",
  "The Prestige",
  "Django Unchained",
  "Naruto",
  "The Departed",
  "Erased",
  "Parasite",
  "Squid Game",
  "Alien",
  "Aliens",
  "Predator",
  "Terminator 2",
  "Ben 10",
  "Back to the Future",
  "Jurassic Park",
  "The Lion King",
  "Toy Story",
  "Stranger Things",
  "Finding Nemo",
  "Shrek",
  "Mad Max",
  "John Wick",
  "The Avengers",
  "Iron Man",
  "Doctor Strange",
  "Spider-Man",
  "Re Zero",
  "Wolverine",
  "Deadpool",
  "Teletubbies",
  "The Conjuring",
  "Insidious",
  "Hereditary",
  "Steven Universe",
  "Midsommar",
  "It",
  "Scream",
  "096",
  "Halloween",
  "The Exorcist",
  "Saw",
  "Regular Show",
  "Blade Runner",
  "Blade Runner 2049",
  "Arrival",
  "The Green Mile",
  "Cast Away",
  "Goodfellas",
  "Casino",
  "Power Rangers",
  "Scarface",
  "Heat",
  "A Quiiet Place"
];

const diccionario = {
  "action": "Acción",
  "romance": "Romance",
  "terror": "Terror",
  "horror": "Horror",
  "suspense": "Suspenso",
  "drama": "Drama",
  "short": "Corto",
  "thriller": "Thriller",
  "comedy": "Comedia",
  "adventure": "Aventura",
  "animation": "Animación",
  "fantasy": "Fantasía",
  "science fiction": "Ciencia ficción",
  "sci-fi": "Ciencia ficción",
  "mystery": "Misterio",
  "crime": "Crimen",
  "detective": "Detectives",
  "war": "Bélico",
  "western": "Western",
  "historical": "Histórico",
  "biography": "Biografía",
  "documentary": "Documental",
  "family": "Familiar",
  "musical": "Musical",
  "music": "Música",
  "sport": "Deportes",
  "superhero": "Superhéroes",
  "history": "Historia",
  "supernatural": "Sobrenatural",
  "psychological": "Psicológico",
  "dystopian": "Distópico",
  "post_apocalyptic": "Postapocalíptico",
  "apocalyptic": "Apocalíptico",
  "survival": "Supervivencia",
};

const descripciones = {
  "Batman" : "El Caballero Oscuro de Gotham City comienza su guerra contra el crimen con su primer gran enemigo, el payaso homicida conocido como el Guasón (Joker).",
  "Better Call Saul" : "Las pruebas y tribulaciones del abogado de causas perdidas Jimmy McGill en los años previos a la creación de su bufete de abogados en Albuquerque, Nuevo México, bajo el alias de Saul Goodman.",
  "Hellraiser" : "Una esposa infiel se encuentra con el zombi de su amante muerto, quien está siendo perseguido por demonios de otra dimensión después de que escapara de ellos mediante un cofre rompecabezas mágico.",
  "Inception" : "A un ladrón que roba secretos corporativos a través del uso de la tecnología de compartir sueños se le da la tarea inversa de plantar una idea en la mente de un director ejecutivo.",
  "The Matrix" : "Cuando una bella desconocida lleva al hacker Neo a un inframundo inhóspito, descubre la terrible verdad: la vida que conoce es el engaño elaborado de una ciber-inteligencia malvada.",
  "Interstellar" : "Cuando la Tierra se vuelve inhabitable en el futuro, un granjero y ex-piloto de la NASA, Joseph Cooper, tiene la tarea de pilotar una nave espacial junto con un equipo de investigadores para encontrar un nuevo planeta para los humanos.",
  "Gladiator" : "Un ex-general romano intenta vengarse del emperador corrupto que asesinó a su familia y lo envió a la esclavitud.",
  "Titanic" : "Una aristócrata de diecisiete años se enamora de un artista amable pero pobre a bordo del lujoso e ilusionante R.M.S. Titanic.",
  "Avatar" : "Un infante de marina parapléjico enviado a la luna Pandora en una misión única se desgarra entre seguir sus órdenes y proteger el mundo que siente que es su hogar.",
  "Dark" : "Una saga familiar con tintes sobrenaturales ambientada en un pueblo alemán, donde la desaparición de dos niños deja al descubierto las dobles vidas y las relaciones rotas entre cuatro familias.",
  "The Godfather" : "El envejecido patriarca de una dinastía del crimen organizado en la ciudad de Nueva York transfiere el control de su imperio clandestino a su reacio hijo.",
  "Pulp Fiction" : "Las vidas de dos asesinos a sueldo, un boxeador, la esposa de un gángster y un par de bandidos de poca monta se entrelazan en cuatro historias de violencia y redención.",
  "Fight Club" : "Un oficinista insomne y un fabricante de jabón descuidado canalizan la agresión masculina primitiva en una nueva forma de terapia escandalosa, su concepto evoluciona hasta convertirse en un plan clandestino para destruir la civilización.",
  "Bleach" : "El estudiante de secundaria Ichigo Kurosaki, que tiene la capacidad de ver fantasmas, adquiere los poderes de un segador de almas (Shinigami) y se dispone a salvar al mundo de los espíritus oscuros llamados Hollows.",
  "The Dark Knight" : "Cuando la amenaza conocida como el Joker causa estragos y caos en la gente de Gotham, Batman debe aceptar una de las mayores pruebas psicológicas y físicas de su capacidad para luchar contra la injusticia.",
  "Forrest Gump" : "La historia de la vida de un hombre con un coeficiente intelectual bajo que presencia y participa sin querer en algunos de los eventos más grandes de la historia de los Estados Unidos del siglo XX.",
  "Joker" : "Arthur Fleck, un payaso de fiesta e inspirador comediante de stand-up con problemas mentales, se ve marginado y maltratado por la sociedad, lo que lo lleva a una espiral de revolución y crimen sangriento en Gotham City.",
  "Chernobyl" : "En abril de 1986, una gran explosión sacude la central nuclear de Chernobyl en Ucrania (Unión Soviética), contando las historias de las personas que sacrificaron sus vidas para evitar un desastre mayor.",
  "Whiplash" : "Un joven y prometedor baterista de jazz se inscribe en un conservatorio de música donde sus sueños de grandeza son guiados por un instructor que no se detendrá ante nada para darse cuenta del potencial de un estudiante.",
  "Dragon Ball Z" : "Con la ayuda de los Guerreros Z, Goku defiende la Tierra de una variedad de villanos intergalácticos que buscan dominar o destruir el planeta.",
  "The Prestige" : "Tras un trágico accidente, dos ilusionistas de la época eduardiana en Londres se enzarzan en una batalla competitiva para crear el truco definitivo, sacrificando todo lo que tienen para superarse mutuamente.",
  "Django Unchained" : "Con la ayuda de un cazarrecompensas alemán, un esclavo liberado se dispone a rescatar a su esposa de un brutal propietario de una plantación en Mississippi.",
  "Naruto" : "Naruto Uzumaki, un ninja adolescente travieso, lucha por ganar el reconocimiento de su aldea y cumplir su sueño de convertirse en el Hokage, el líder de la comunidad.",
  "The Departed" : "Un agente encubierto y un topo en la policía intentan identificarse mutuamente mientras se infiltran en una banda irlandesa en el sur de Boston.",
  "Erased" : "Satoru Fujinuma, un joven con la habilidad de viajar en el tiempo unos minutos antes de un desastre, es enviado 18 años al pasado para evitar el secuestro y asesinato de sus compañeros de clase.",
  "Parasite" : "La codicia y la discriminación de clases amenazan la relación simbiótica recién formada entre la rica familia Park y el clan Kim, que carece de recursos económicos.",
  "Squid Game" : "Cientos de jugadores cortos de dinero aceptan una extraña invitación a competir en juegos infantiles. Dentro, les espera un premio tentador con apuestas mortales de alto riesgo.",
  "Alien" : "El equipo de una nave espacial comercial se encuentra con una forma de vida mortal después de investigar un misterioso SOS proveniente de un planeta distante.",
  "Aliens" : "Décadas después de que Ellen Ripley sobreviviera a la masacre de su nave, regresa al planeta donde se encontró por primera vez con la criatura alienígena, esta vez acompañada por marines coloniales.",
  "Predator" : "Un equipo de comandos en una misión en una jungla centroamericana se encuentra siendo perseguido por un guerrero extraterrestre tecnológicamente avanzado.",
  "Terminator 2" : "Un cyborg, idéntico al que falló en matar a Sarah Connor años atrás, debe proteger ahora a su hijo adolescente, John Connor, de un cyborg más avanzado y líquido.",
  "Ben 10" : "Ben Tennyson, un niño de 10 años, descubre un misterioso dispositivo alienígena tipo reloj llamado Omnitrix, que le permite transformarse en diez especies extraterrestres diferentes.",
  "Back to the Future" : "Marty McFly, un estudiante de secundaria de 17 años, es enviado accidentalmente treinta años al pasado en un DeLorean que viaja en el tiempo, inventado por su amigo científico Doc Brown.",
  "Jurassic Park" : "Un pragmático paleontólogo que visita un parque temático casi completo en una isla de América Central tiene la tarea de proteger a una pareja de niños después de que un corte de energía provoca que los dinosaurios clonados del parque queden en libertad.",
  "The Lion King" : "El cachorro de león Simba es engañado por su traicionero tío para creer que él causó la muerte de su padre Mufasa, huyendo al exilio antes de regresar para reclamar su trono.",
  "Toy Story" : "Un muñeco vaquero de juguete se siente profundamente amenazado y celoso cuando una nueva figura de acción de un guardián espacial lo reemplaza como el juguete favorito en la habitación de un niño.",
  "Stranger Things" : "Cuando un niño desaparece en un pequeño pueblo, sus amigos descubren un misterio que involucra experimentos secretos del gobierno, fuerzas sobrenaturales aterradoras y a una niña muy extraña.",
  "Finding Nemo" : "Después de que su hijo sea capturado en la Gran Barrera de Coral y llevado a Sydney, un tímido pez payaso emprende un peligroso viaje para traerlo de vuelta a casa.",
  "Shrek" : "Un ogro de modales toscos encuentra su hogar en el pantano invadido por criaturas de cuentos de hadas desterradas por el obsesivo Lord Farquaad, y hace un trato para rescatar a una princesa para recuperar su tierra.",
  "Mad Max" : "En un páramo postapocalíptico, una mujer se rebela contra un gobernante tiránico en busca de su patria con la ayuda de un grupo de prisioneras psicóticas, un adorador de la guerra y un vagabundo llamado Max.",
  "John Wick" : "Un ex-asesino a sueldo regresa al submundo criminal del que se retiró para cazar a los mafiosos que arruinaron su vida y mataron a su perro.",
  "The Avengers" : "Los héroes más poderosos de la Tierra deben unirse y aprender a luchar como un equipo si quieren detener al travieso Loki y su ejército alienígena antes de que esclavicen a la humanidad.",
  "Iron Man" : "Después de ser retenido en cautiverio en una cueva afgana, el multimillonario ingeniero Tony Stark crea una armadura armada única para luchar contra el mal.",
  "Doctor Strange" : "Mientras viaja en un viaje físico y espiritual de curación, un brillante pero arrogante neurocirujano se ve arrastrado al mundo de las artes místicas.",
  "Spider Man" : "Después de ser mordido por una araña genéticamente modificada, un estudiante de secundaria tímido y nerd adquiere habilidades increíbles que debe usar para luchar contra la injusticia y un supervillano mutado.",
  "Re Zero" : "Subaru Natsuki es transportado repentinamente a un mundo de fantasía donde descubre que tiene la capacidad de regresar en el tiempo cada vez que muere, usándola para salvar a sus nuevos amigos.",
  "Logan" : "En un futuro cercano, un cansado Logan cuida de un enfermo Profesor X en algún lugar de la frontera con México. Sin embargo, los intentos de Logan de esconderse del mundo y de su legado concluyen cuando llega una joven mutante perseguida por fuerzas oscuras.",
  "Deadpool" : "Un ex-mercenario de las Fuerzas Especiales que adoptó una identidad alterada y poderes de curación acelerada tras un experimento fallido, busca venganza contra el hombre que destruyó sus rasgos físicos.",
  "Teletubbies" : "Las aventuras de cuatro coloridos personajes infantiles hiperactivos (Tinky Winky, Dipsy, Laa-Laa y Po) en un paisaje futurista con pantallas en sus estómagos.",
  "The Conjuring" : "Los investigadores paranormales Ed y Lorraine Warren trabajan para ayudar a una familia aterrorizada por una presencia oscura y demoníaca en su granja aislada.",
  "Insidious" : "Una familia busca evitar que los espíritus malignos atrapen a su hijo comatoso en un reino misterioso llamado 'El Más Allá'.",
  "Hereditary" : "Una familia en duelo es acosada por trágicos y perturbadores sucesos después de la muerte de la matriarca secreta, desentrañando oscuros secretos sobre sus ancestros.",
  "Steven Universe" : "Un joven mitad humano, mitad gema mágica llamado Steven crece junto a las Gemas de Cristal, tres guerreras alienígenas que protegen al universo de las amenazas de su propia especie.",
  "Midsommar" : "Una pareja viaja a Escandinavia para visitar el festival de verano de la ciudad natal de un amigo rural, solo para encontrarse en medio de una violenta y extraña competencia pagana.",
  "It" : "En el verano de 1989, un grupo de niños marginados se une para destruir a un monstruo que cambia de forma, que se disfraza de payaso y asesina a los niños de su pequeño pueblo en Maine.",
  "Scream" : "Un año después del asesinato de su madre, una joven estudiante de secundaria es aterrorizada por un nuevo asesino en serie que utiliza las películas de terror como parte de un juego mortal.",
  "SCP-096" : "Cortometraje basado en el universo de la Fundación SCP, centrado en los eventos que rodean la contención del SCP-096, un humanoide alto y pálido que ataca agresivamente a cualquiera que vea su rostro.",
  "Halloween" : "Quince años después de asesinar a su hermana en la noche de Halloween de 1963, Michael Myers escapa de un hospital psiquiátrico y regresa al pequeño pueblo de Haddonfield para volver a matar.",
  "The Exorcist" : "Cuando una joven es poseída por una entidad misteriosa, su madre busca la ayuda de dos sacerdotes católicos para salvar a su hija mediante un exorcismo.",
  "Saw" : "Dos hombres se despiertan atrapados en una habitación subterránea en descomposición, donde un asesino en serie conocido como Jigsaw les da órdenes e instrucciones a través de cintas de audio para jugar un juego mortal por sus vidas.",
  "Regular Show" : "La vida cotidiana de dos amigos de veinte años, un azulejo llamado Mordecai y un mapache llamado Rigby, que trabajan como jardineros en un parque local y transforman sus tareas diarias en incidentes surrealistas e hiperbólicos.",
  "Blade Runner" : "Un blade runner debe perseguir y rescindir a cuatro replicantes que robaron una nave espacial en el espacio y regresaron a la Tierra para buscar a su creador.",
  "Blade Runner 2049" : "Un nuevo blade runner del departamento de policía de Los Ángeles, el Oficial K, descubre un secreto enterrado desde hace mucho tiempo que tiene el potencial de sumergir lo que queda de la sociedad en el caos.",
  "Arrival" : "Una lingüista es reclutada por el ejército para comunicarse con formas de vida extraterrestres después de que doce naves espaciales misteriosas aparecen en todo el mundo.",
  "The Green Mile" : "Las vidas de los guardias del corredor de la muerte en una prisión durante la Gran Depresión se ven afectadas por uno de sus reclusos: un hombre negro de gran tamaño acusado de asesinato que posee un don milagroso de curación.",
  "Cast Away" : "Un ejecutivo de FedEx sufre un accidente aéreo y queda varado en una isla desierta en el Océano Pacífico, donde debe usar la transformación física y mental para sobrevivir.",
  "Goodfellas" : "La historia de Henry Hill y su vida en la mafia, cubriendo su relación con su esposa Karen Hill y sus socios criminales Jimmy Conway y Tommy DeVito en el sindicato del crimen italoamericano.",
  "Casino" : "En Las Vegas, un apostador de bajo perfil es elegido por la mafia para dirigir el Casino Tangiers, donde la ambición, la codicia y el engaño destruyen su imperio y su vida.",
  "Power Rangers" : "Un grupo de adolescentes de secundaria con talentos únicos y pasados conflictivos adquieren superpoderes extraterrestres y deben unirse para salvar al mundo de una amenaza alienígena.",
  "Scarface" : "En Miami en 1980, un refugiado cubano decidido y decidido se hace cargo de un cartel de drogas y sucumbe a la codicia pura y la paranoia.",
  "Heat" : "Un grupo de ladrones de bancos profesionales comienza a sentir la presión de la policía de Los Ángeles cuando un detective obsesionado se propone atraparlos tras un golpe que salió mal.",
  "A Quiet Place" : "En un mundo postapocalíptico, una familia se ve obligada a vivir en total silencio mientras se esconde de monstruos ciegos que poseen un sentido del oído ultra sensible."
}
