const listaPeliculas = [
  "Batman",
  "Better Call Saul",
  "Hellraiser",
  "Inception",
  "The Matrix",
  "Interstellar",
  "Gladiator",
  "Titanic",
  "Avatar",
  "The Godfather",
  "Pulp Fiction",
  "Fight Club",
  "The Dark Knight",
  "Forrest Gump",
  "The Shawshank Redemption",
  "Joker",
  "The Silence of the Lambs",
  "Se7en",
  "Whiplash",
  "The Prestige",
  "Django Unchained",
  "The Departed",
  "Parasite",
  "Alien",
  "Aliens",
  "Predator",
  "Terminator 2: Judgment Day",
  "Back to the Future",
  "Jurassic Park",
  "The Lion King",
  "Toy Story",
  "Finding Nemo",
  "Shrek",
  "Mad Max: Fury Road",
  "John Wick",
  "The Avengers",
  "Iron Man",
  "Doctor Strange",
  "Spider-Man",
  "Logan",
  "Deadpool",
  "The Conjuring",
  "Insidious",
  "Hereditary",
  "Midsommar",
  "It",
  "Scream",
  "Halloween",
  "A Nightmare on Elm Street",
  "The Exorcist",
  "Saw",
  "Blade Runner",
  "Blade Runner 2049",
  "Arrival",
  "The Green Mile",
  "Cast Away",
  "Goodfellas",
  "Casino",
  "Scarface",
  "Heat",
  "a silent place"
];

const diccionario = {
  "action": "Acción",
  "romance": "Romance",
  "terror": "Terror",
  "horror": "Horror",
  "suspense": "Suspenso",
  "drama": "Drama",
  "thriller": "Thriller",
  "comedy": "Comedia",
  "adventure": "Aventura",
  "animation": "Animación",
  "fantasy": "Fantasía",
  "science_fiction": "Ciencia ficción",
  "sci fi": "Ciencia ficción",
  "mystery": "Misterio",
  "crime": "Crimen",
  "detective": "Detectives",
  "war": "Bélico",
  "western": "Western",
  "historical": "Histórico",
  "biography": "Biografía",
  "documentary": "Documental",
  "family": "Familiar",
  "musical": "Musical",
  "music": "Música",
  "sport": "Deportes",
  "superhero": "Superhéroes",
  "supernatural": "Sobrenatural",
  "psychological": "Psicológico",
  "dystopian": "Distópico",
  "post_apocalyptic": "Postapocalíptico",
  "apocalyptic": "Apocalíptico",
  "survival": "Supervivencia",
};
